language: python
python: "3.7"
dist: xenial

stages:
  - name: release
    if: tag IS present

cache:
  paths:
    - venv

install:
  - virtualenv -p python venv
  - source venv/bin/activate
  - pip install -r requirements.txt


jobs:
  include:
    - stage: test
      before_script:
        - pip install pytest
      python:
        - "3.7"
      script:
        - python3.7 -m pytest test
    - stage: release
      before_script:
        - pip install kaggle
        - export KAGGLE_USERNAME=${KAGGLE_USERNAME}
        - export KAGGLE_KEY=${KAGGLE_KEY}
      script:
        - kaggle competitions submit -c halite -f submission.py -m "${TRAVIS_TAG}"